/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pa_18131273_proyecto_01;

import java.text.DecimalFormat;
import javax.swing.table.DefaultTableModel;
import java.awt.Image;
import java.awt.Toolkit;
/**
 *
 * @author Jose angel
 */
public class PA_18131273_Frame_01 extends javax.swing.JFrame {
    /**
     * Creates new form PA_18131273_Frame_01
     */

    ArregloCircuitos circuitosTabla;//Arreglo de objeto circuito
    ArregloCircuitos ejemplos = new ArregloCircuitos(3);
    int posicion;//posicion del jSpin
    DecimalFormat d = new DecimalFormat("#####.0000");
    public PA_18131273_Frame_01() {
       initComponents();
    
      jTableCircuitos.setShowGrid(true);//mostrar lineas en tabla
      jTextEstablecer.setText(String.valueOf(0));//Establecer valor de 0 para jtextEstablecer
       //Bloqueo de botones si no hay datos establecidos
        if(Integer.parseInt(jTextEstablecer.getText()) == 0){
                   jButEditar.setEnabled(false);
                   jButEditar.setEnabled(false);
                   jButAleatorios.setEnabled(false);
                   jButAlfabetico.setEnabled(false);
                   jButDescendente.setEnabled(false);
                   jButGrabar.setEnabled(false);
                   jButMayMen.setEnabled(false);
        }            
    }
    //Metodo para mostrar valores en la tabla
    public void mostrar(){
         double sumaR = 0,totalXl= 0,sumaXc=0,totalZ=0;
          for(int r=0;r<jTableCircuitos.getRowCount();r++){
            jTableCircuitos.setValueAt(circuitosTabla.getCircuito(r).getNombre(),r,0);
            jTableCircuitos.setValueAt(circuitosTabla.getCircuito(r).getResistencia()+"",r,1);
            jTableCircuitos.setValueAt(circuitosTabla.getCircuito(r).getReactanciaInductiva()+"",r,2);
            jTableCircuitos.setValueAt(circuitosTabla.getCircuito(r).getReactanciaCapacitiva()+"",r,3);
            jTableCircuitos.setValueAt(d.format(circuitosTabla.getCircuito(r).calcularImpedancia()), r, 4);
            
          
            }
    }
    //icono  de la app 
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("pa_18131273_proyecto_01/icono.png"));
        return retValue;
       }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextResistencia = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextReactanciaInductiva = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextReactanciaCapacitiva = new javax.swing.JTextField();
        jButGrabar = new javax.swing.JButton();
        jButAleatorios = new javax.swing.JButton();
        jCheckBoxIncrementar = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jSpinPosicion = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCircuitos = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jButAlfabetico = new javax.swing.JButton();
        jButDescendente = new javax.swing.JButton();
        jButMayMen = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabMayor = new javax.swing.JLabel();
        jLabMenor = new javax.swing.JLabel();
        jButEditar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextEstablecer = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButEstablecerNumero = new javax.swing.JButton();
        jButMostrarOcultar = new javax.swing.JToggleButton();
        jLabel14 = new javax.swing.JLabel();
        jLabelprom = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabPromedioR = new javax.swing.JLabel();
        jLabTotalXl = new javax.swing.JLabel();
        jLabPromedioXc = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabTotalZ = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PA_18131273_Proyecto_01");
        setIconImage(getIconImage());
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel1.setText("Resistencia (R)");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setText("Reactancia Inductiva (XL)");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel4.setText("Reactancia Capacitiva (Xc)");

        jButGrabar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jButGrabar.setText("Grabar");
        jButGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButGrabarActionPerformed(evt);
            }
        });

        jButAleatorios.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jButAleatorios.setText("Aleatorios");
        jButAleatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAleatoriosActionPerformed(evt);
            }
        });

        jCheckBoxIncrementar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBoxIncrementar.setText("Incrementar");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel5.setText("Posición");

        jSpinPosicion.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jSpinPosicion.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinPosicionStateChanged(evt);
            }
        });

        jTableCircuitos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "R", "XL", "Xc", "Z"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableCircuitos);
        if (jTableCircuitos.getColumnModel().getColumnCount() > 0) {
            jTableCircuitos.getColumnModel().getColumn(0).setResizable(false);
            jTableCircuitos.getColumnModel().getColumn(1).setResizable(false);
            jTableCircuitos.getColumnModel().getColumn(2).setResizable(false);
            jTableCircuitos.getColumnModel().getColumn(3).setResizable(false);
            jTableCircuitos.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel7.setText("Ordenar por ");

        jButAlfabetico.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jButAlfabetico.setText("Alfabetico");
        jButAlfabetico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAlfabeticoActionPerformed(evt);
            }
        });

        jButDescendente.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jButDescendente.setText("Impedancia");
        jButDescendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButDescendenteActionPerformed(evt);
            }
        });

        jButMayMen.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jButMayMen.setText("Mayor y menor");
        jButMayMen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButMayMenActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel8.setText("Mayor");

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel9.setText("Menor");

        jLabMayor.setBackground(new java.awt.Color(153, 255, 255));
        jLabMayor.setOpaque(true);

        jLabMenor.setBackground(new java.awt.Color(153, 255, 255));
        jLabMenor.setOpaque(true);

        jButEditar.setText("Editar");
        jButEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButEditarActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel10.setText("No.Datos");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pa_18131273_proyecto_01/proyecto_asign.png"))); // NOI18N
        jLabel11.setOpaque(true);

        jLabel6.setText("Nombre del alumno: José Ángel Rocha García  ");

        jLabel12.setText("No.de control: 18131273");

        jLabel13.setText("No. de proyecto: 1");

        jButEstablecerNumero.setText("Establecer");
        jButEstablecerNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButEstablecerNumeroActionPerformed(evt);
            }
        });

        jButMostrarOcultar.setText("Mostrar/ocultar ejemplo");
        jButMostrarOcultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButMostrarOcultarActionPerformed(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(153, 255, 255));
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Suma/Promedio");
        jLabel14.setOpaque(true);

        jLabelprom.setBackground(new java.awt.Color(153, 255, 255));
        jLabelprom.setForeground(new java.awt.Color(0, 0, 0));
        jLabelprom.setText("Promedio=");
        jLabelprom.setOpaque(true);

        jLabel16.setBackground(new java.awt.Color(153, 255, 255));
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Total=");
        jLabel16.setOpaque(true);

        jLabel17.setBackground(new java.awt.Color(153, 255, 255));
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Promedio=");
        jLabel17.setOpaque(true);

        jLabPromedioR.setBackground(new java.awt.Color(153, 255, 255));
        jLabPromedioR.setOpaque(true);

        jLabTotalXl.setBackground(new java.awt.Color(153, 255, 255));
        jLabTotalXl.setForeground(new java.awt.Color(0, 0, 0));
        jLabTotalXl.setOpaque(true);

        jLabPromedioXc.setBackground(new java.awt.Color(153, 255, 255));
        jLabPromedioXc.setForeground(new java.awt.Color(0, 0, 0));
        jLabPromedioXc.setOpaque(true);

        jLabel15.setBackground(new java.awt.Color(153, 255, 255));
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Total=");
        jLabel15.setOpaque(true);

        jLabTotalZ.setBackground(new java.awt.Color(153, 255, 255));
        jLabTotalZ.setForeground(new java.awt.Color(0, 0, 0));
        jLabTotalZ.setOpaque(true);

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pa_18131273_proyecto_01/descripcion.png"))); // NOI18N

        jLabel18.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        jLabel18.setText("Nombre");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel1)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextResistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextReactanciaInductiva, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jTextReactanciaCapacitiva, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButGrabar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButEditar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButAleatorios)
                            .addComponent(jCheckBoxIncrementar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelprom)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabPromedioR, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabTotalXl, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabPromedioXc, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabTotalZ, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 764, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel13)
                                            .addGap(137, 137, 137))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel12)))
                                    .addComponent(jLabel19))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jButMostrarOcultar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(jButMayMen))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel8))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabMayor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabMenor, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel10)
                                            .addGap(8, 8, 8)
                                            .addComponent(jTextEstablecer, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButEstablecerNumero))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(73, 73, 73)
                                            .addComponent(jLabel7))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jButDescendente, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jButAlfabetico, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(jLabel5)
                                .addComponent(jSpinPosicion)
                                .addComponent(jLabel2)
                                .addComponent(jCheckBoxIncrementar))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextResistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextReactanciaInductiva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextReactanciaCapacitiva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButEditar)
                                .addComponent(jButGrabar))
                            .addComponent(jButAleatorios))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabPromedioR, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel14)
                                .addComponent(jLabelprom))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel17)
                                .addComponent(jLabPromedioXc, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16)
                                .addComponent(jLabTotalXl, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel15)
                                .addComponent(jLabTotalZ, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel19))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextEstablecer, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButEstablecerNumero))
                        .addGap(33, 33, 33)
                        .addComponent(jButMostrarOcultar)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButDescendente)
                            .addComponent(jButAlfabetico))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButMayMen)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(8, 8, 8)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30))
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabMayor, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabMenor, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(149, 149, 149)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    private void jButMayMenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButMayMenActionPerformed
        //Accion para ejemplo
        if(jButMostrarOcultar.isSelected()){
             jLabMayor.setText(ejemplos.mayor());
             jLabMenor.setText(ejemplos.menor());
        }
        //////////////////////////////7
        else{
             jLabMayor.setText(circuitosTabla.mayor());//Establecer circuito con mayor impedancia
             jLabMenor.setText(circuitosTabla.menor());//Establecer circuito con menor impedancia
        }
    }//GEN-LAST:event_jButMayMenActionPerformed

    private void jSpinPosicionStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinPosicionStateChanged
      //Validar posicion tamaño     
      posicion = (int)jSpinPosicion.getValue()-1;//añadir valor del spinner a posicion
      int valorEstablecer = Integer.parseInt(jTextEstablecer.getText());
      if(posicion>=valorEstablecer)//Si el valor del spinner intenta superar el valor maximo
                jSpinPosicion.setValue(valorEstablecer);//Se pone el valor maximo como limite
    }//GEN-LAST:event_jSpinPosicionStateChanged

    private void jButGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButGrabarActionPerformed
        //Grabar valores de los jText al jTableCircuitos y al arreglo de objetos
        //nombre
        jTableCircuitos.setValueAt(jTextNombre.getText(),posicion,0);
         circuitosTabla.getCircuito(posicion).setNombre(jTextNombre.getText());  
        //Resistencia
        jTableCircuitos.setValueAt(jTextResistencia.getText(),posicion,1);
        circuitosTabla.getCircuito(posicion).setResistencia(Double.parseDouble(jTextResistencia.getText()) );
        //ReactanciaInductiva
        jTableCircuitos.setValueAt(jTextReactanciaInductiva.getText(),posicion,2);
        circuitosTabla.getCircuito(posicion).setReactanciaInductiva (Double.parseDouble(jTextReactanciaInductiva.getText()));
        //ReactanciaCapacitiva
        jTableCircuitos.setValueAt(jTextReactanciaCapacitiva.getText(),posicion,3);
        circuitosTabla.getCircuito(posicion).setReactanciaCapacitiva(Double.parseDouble(jTextReactanciaCapacitiva.getText()));
        //Grabar impedancia a tabla con ayuda de metodo de objeto circuito
        jTableCircuitos.setValueAt(d.format(circuitosTabla.getCircuito(posicion).calcularImpedancia()), posicion, 4);

        //Calcular sumas y promedios
        double sumaR = 0,totalXl= 0,sumaXc=0,totalZ=0;
        for(int i=0; i<circuitosTabla.getTamaño();i++){
             sumaR += circuitosTabla.getCircuito(i).getResistencia();
            totalXl += circuitosTabla.getCircuito(i).getReactanciaInductiva();
            sumaXc += circuitosTabla.getCircuito(i).getReactanciaCapacitiva();
            totalZ += circuitosTabla.getCircuito(i).calcularImpedancia();
        }
       //Establecer sumas y promedios
            jLabPromedioR.setText(d.format(sumaR/circuitosTabla.getTamaño())+"");
            jLabTotalXl.setText(d.format(totalXl)+"");
            jLabPromedioXc.setText(d.format(sumaXc/circuitosTabla.getTamaño())+"");
            jLabTotalZ.setText(d.format(totalZ)+"");
 
        //Incremento automatico
         if(jCheckBoxIncrementar.isSelected())
            if(posicion==jTableCircuitos.getRowCount()-1)
                jSpinPosicion.setValue(1);
        else
            jSpinPosicion.setValue(posicion+2);
    }//GEN-LAST:event_jButGrabarActionPerformed

    private void jButAleatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAleatoriosActionPerformed
        //Agregar valores aleatorios a la tabla
        jTextNombre.setText(circuitosTabla.nombreAleatorio());
        jTextResistencia.setText(circuitosTabla.valorAleatorio()+"");
        jTextReactanciaInductiva.setText(circuitosTabla.valorAleatorio()+"");
        //Obtener un valor menor a la reactancia inductiva para la reactancia capacitva
        double valorCap = (Double.parseDouble(jTextReactanciaInductiva.getText()) -circuitosTabla.valorAleatorio());
        if(valorCap < 0)
            valorCap *= -1;
        if(valorCap > Double.parseDouble(jTextReactanciaInductiva.getText()) )
            valorCap = Double.parseDouble(jTextReactanciaInductiva.getText()) -30;
        jTextReactanciaCapacitiva.setText(valorCap +"");  
    }//GEN-LAST:event_jButAleatoriosActionPerformed

    private void jButAlfabeticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAlfabeticoActionPerformed
     //Accion para ejemplo
        if(jButMostrarOcultar.isSelected()){
            ejemplos.ordenarAlfabetico(); 
            for(int r=0;r<ejemplos.getTamaño(); r++){
            jTableCircuitos.setValueAt(ejemplos.getCircuito(r).getNombre(),r,0);
            jTableCircuitos.setValueAt(ejemplos.getCircuito(r).getResistencia()+"",r,1);
            jTableCircuitos.setValueAt(ejemplos.getCircuito(r).getReactanciaInductiva()+"",r,2);
            jTableCircuitos.setValueAt(ejemplos.getCircuito(r).getReactanciaCapacitiva()+"",r,3);
            jTableCircuitos.setValueAt(d.format(ejemplos.getCircuito(r).calcularImpedancia()), r, 4);
            }
        }
        ///////////////////////////////////////
        else{
            circuitosTabla.ordenarAlfabetico();
            mostrar();//Mostrar el arreglo
        }
    }//GEN-LAST:event_jButAlfabeticoActionPerformed

    private void jButDescendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButDescendenteActionPerformed
    //Accion para ejemplo
        if(jButMostrarOcultar.isSelected()){
            ejemplos.impedanciaDescendente();
            for(int r=0;r<ejemplos.getTamaño(); r++){
            jTableCircuitos.setValueAt(ejemplos.getCircuito(r).getNombre(),r,0);
            jTableCircuitos.setValueAt(ejemplos.getCircuito(r).getResistencia()+"",r,1);
            jTableCircuitos.setValueAt(ejemplos.getCircuito(r).getReactanciaInductiva()+"",r,2);
            jTableCircuitos.setValueAt(ejemplos.getCircuito(r).getReactanciaCapacitiva()+"",r,3);
            jTableCircuitos.setValueAt(d.format(ejemplos.getCircuito(r).calcularImpedancia()), r, 4);
            }
        }  
        /////////////////////////////////////7
        else{ 
        circuitosTabla.impedanciaDescendente();
         mostrar();
        }
    }//GEN-LAST:event_jButDescendenteActionPerformed

    private void jButEstablecerNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButEstablecerNumeroActionPerformed
      //Si la cantidad insertada no es cero no agrega renglones al jtable, especificados en el jTextEstablecer y bloquea el boton restablecer
       if(Integer.parseInt(jTextEstablecer.getText())  !=0){
            DefaultTableModel modelo = (DefaultTableModel)jTableCircuitos.getModel();   //obtener el modelo de la tabla
            modelo.setRowCount(Integer.parseInt(jTextEstablecer.getText()));//Se obtiene el numero del jText y ese establece el tamaño deseado
            //Desactivar el boton establecer para no modificar el arreglo creado
            jButEstablecerNumero.setEnabled(false);
           //Habilitar botones
           jButEditar.setEnabled(true);
           jButAleatorios.setEnabled(true);
           jButDescendente.setEnabled(true); 
           jButAlfabetico.setEnabled(true);
           jButMayMen.setEnabled(true);
           jButGrabar.setEnabled(true);
           this.circuitosTabla = new ArregloCircuitos(   Integer.parseInt(jTextEstablecer.getText()) );//Arreglo con la dimension de jtextEstablecer
       }
    }//GEN-LAST:event_jButEstablecerNumeroActionPerformed

    private void jButEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButEditarActionPerformed
        if(jTextNombre.getText().length() != 0){//Comprobar si el jTextnombre tiene nuevos datos 
        jTableCircuitos.setValueAt(jTextNombre.getText(), posicion, 0);//Colocamos el nuevo valor en la tabla
        circuitosTabla.getCircuito( posicion).setNombre(jTextNombre.getText());//Colocamos el nuevo valor al objeto
        }
        
        if(jTextResistencia.getText().length() != 0){//Comprobar si el campo jTextResistencia tiene nuevos datos
        jTableCircuitos.setValueAt(Double.parseDouble(jTextResistencia.getText()), posicion, 1);//Colocamos el nuevo valor en la tabla
        circuitosTabla.getCircuito( posicion).setResistencia(Double.parseDouble(jTextResistencia.getText() ));//Colocamos el nuevo valor al objeto
        }
        
        if(jTextReactanciaInductiva.getText().length() != 0){//Comprobar si el campo jTextReactInducitva tiene nuevos datos
        jTableCircuitos.setValueAt(Double.parseDouble(jTextReactanciaInductiva.getText()), posicion, 2);//Colocamos el valor en la tabla
        circuitosTabla.getCircuito( posicion).setReactanciaInductiva(Double.parseDouble(jTextReactanciaInductiva.getText() ));//Colocamos el nuevo valor al objeto
        }
    
        if(jTextReactanciaCapacitiva.getText().length() != 0){//Comprobar si el campo jTextReact Capacitiva tiene nuevos datos
        jTableCircuitos.setValueAt(Double.parseDouble(jTextReactanciaCapacitiva.getText()), posicion, 3);//Colocamos el valor en la tabla
        circuitosTabla.getCircuito( posicion).setReactanciaCapacitiva(Double.parseDouble(jTextReactanciaCapacitiva.getText() ));//Colocamos el nuevo valor al objeto
        }
     
        double sumaR=0,totalXl=0,sumaXc=0,totalZ=0;
        //calcular valores suma y promedios con los nuevos datos
         for(int r=0;r<ejemplos.getTamaño();r++){
            jTableCircuitos.setValueAt(d.format(circuitosTabla.getCircuito(r).calcularImpedancia()) ,r,4);
            sumaR += circuitosTabla.getCircuito(r).getResistencia();
            totalXl +=  circuitosTabla.getCircuito(r).getReactanciaInductiva();
            sumaXc += circuitosTabla.getCircuito(r).getReactanciaCapacitiva();
            totalZ +=  circuitosTabla.getCircuito(r).calcularImpedancia();
            //Establecer Valores suma /promedio
            jLabPromedioR.setText(d.format(sumaR/circuitosTabla.getTamaño()) );
            jLabTotalXl.setText(d.format(totalXl) );
            jLabPromedioXc.setText(d.format(sumaXc/ circuitosTabla.getTamaño() ));
            jLabTotalZ.setText(d.format(totalZ) );
            }  
        
    }//GEN-LAST:event_jButEditarActionPerformed

    private void jButMostrarOcultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButMostrarOcultarActionPerformed
         boolean valoresBorrados=false;
         //Agregar 3 renlones a la tabla
        DefaultTableModel modelo = (DefaultTableModel)jTableCircuitos.getModel();
        modelo.setRowCount(3);
        
        //ArregloCircuitos ejemplos = new ArregloCircuitos(jTableCircuitos.getRowCount());
        //Objeto ejemplo 1
        ejemplos.getCircuito(0).setNombre("M-18");
        ejemplos.getCircuito(0).setResistencia(50);
        ejemplos.getCircuito(0).setReactanciaInductiva(15);
        ejemplos.getCircuito(0).setReactanciaCapacitiva(3);
        //Objeto ejemplo 2
        ejemplos.getCircuito(1).setNombre("C-12");
        ejemplos.getCircuito(1).setResistencia(20);
        ejemplos.getCircuito(1).setReactanciaInductiva(30);
        ejemplos.getCircuito(1).setReactanciaCapacitiva(2);
        //Objeto ejemplo 3
        ejemplos.getCircuito(2).setNombre("F-45");
        ejemplos.getCircuito(2).setResistencia(80);
        ejemplos.getCircuito(2).setReactanciaInductiva(45);
        ejemplos.getCircuito(2).setReactanciaCapacitiva(1);
        //Se muestra el ejemplo
        double sumaR = 0,totalXl= 0,sumaXc=0,totalZ=0;
        if(jButMostrarOcultar.isSelected()){
            //Desactivar botones para impedir modificacion de ejemplo y activar ordenamientos
            jButEditar.setEnabled(false);
            jButGrabar.setEnabled(false);
            jButAleatorios.setEnabled(false);
           jButDescendente.setEnabled(true); 
           jButAlfabetico.setEnabled(true);
           jButMayMen.setEnabled(true);
           //////////////////////////////////////
           //Borramos los valores mayor y menor
            jLabMayor.setText("");
            jLabMenor.setText("");  
            /////////////////////////////
            for(int r=0;r<jTableCircuitos.getRowCount();r++){
            jTableCircuitos.setValueAt(ejemplos.getCircuito(r).getNombre(),r,0);
            jTableCircuitos.setValueAt(ejemplos.getCircuito(r).getResistencia()+"",r,1);
            jTableCircuitos.setValueAt(ejemplos.getCircuito(r).getReactanciaInductiva()+"",r,2);
            jTableCircuitos.setValueAt(ejemplos.getCircuito(r).getReactanciaCapacitiva()+"",r,3);
            jTableCircuitos.setValueAt(d.format(ejemplos.getCircuito(r).calcularImpedancia()), r, 4);
            }
        //calcular valores suma y promedios
         for(int r=0;r<ejemplos.getTamaño();r++){
            sumaR += ejemplos.getCircuito(r).getResistencia();
            totalXl += ejemplos.getCircuito(r).getReactanciaInductiva();
            sumaXc += ejemplos.getCircuito(r).getReactanciaCapacitiva();
            totalZ += ejemplos.getCircuito(r).calcularImpedancia();
            //Establecer Valores suma /promedio
            jLabPromedioR.setText(d.format(sumaR/ejemplos.getTamaño()));
            jLabTotalXl.setText(d.format(totalXl));
            jLabPromedioXc.setText(d.format(sumaXc/ejemplos.getTamaño()));
            jLabTotalZ.setText(d.format(totalZ));
            } 
        } 
        //Borrar valores de ejemplos
         else{
            for(int r=0;r<jTableCircuitos.getRowCount();r++){
            jTableCircuitos.setValueAt("",r,0);
            jTableCircuitos.setValueAt("",r,1);
            jTableCircuitos.setValueAt("",r,2);
            jTableCircuitos.setValueAt("",r,3);
            jTableCircuitos.setValueAt("",r,4);   
            // Borrar valores suma y promedios
             }
            jLabPromedioR.setText("");
            jLabTotalXl.setText("");
            jLabPromedioXc.setText("");
            jLabTotalZ.setText(""); 
            jLabMayor.setText("");
            jLabMenor.setText("");  
            valoresBorrados =true;
            modelo.setRowCount(0);
        }
       //Desactivar botones si no hay valor establecido
        if(Integer.parseInt(jTextEstablecer.getText()) == 0   && jTableCircuitos.getRowCount() == 0){
           jButDescendente.setEnabled(false); 
           jButAlfabetico.setEnabled(false);
           jButMayMen.setEnabled(false);
        }
         //cuando los valores se borren y la tabla tenga datos recuperar los valores guardados 
        if(valoresBorrados && Integer.parseInt(jTextEstablecer.getText()) != 0){
            //Activar botones en caso de que se desactivaran
            jButEditar.setEnabled(true);
            jButGrabar.setEnabled(true);
            jButAleatorios.setEnabled(true);
            ///////////////////////////////////////
            modelo.setRowCount(circuitosTabla.getTamaño());
            mostrar();

          
       //Calcular sumas y promedios
        for(int i=0; i<circuitosTabla.getTamaño();i++){
             sumaR += circuitosTabla.getCircuito(i).getResistencia();
            totalXl += circuitosTabla.getCircuito(i).getReactanciaInductiva();
            sumaXc += circuitosTabla.getCircuito(i).getReactanciaCapacitiva();
            totalZ += circuitosTabla.getCircuito(i).calcularImpedancia();
        }
       //Establecer sumas y promedios
            jLabPromedioR.setText(d.format(sumaR/circuitosTabla.getTamaño()));
            jLabTotalXl.setText(d.format(totalXl));
            jLabPromedioXc.setText(d.format(sumaXc/circuitosTabla.getTamaño()));
            jLabTotalZ.setText(d.format(totalZ));
        }
    }//GEN-LAST:event_jButMostrarOcultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PA_18131273_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PA_18131273_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PA_18131273_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PA_18131273_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PA_18131273_Frame_01().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButAleatorios;
    private javax.swing.JButton jButAlfabetico;
    private javax.swing.JButton jButDescendente;
    private javax.swing.JButton jButEditar;
    private javax.swing.JButton jButEstablecerNumero;
    private javax.swing.JButton jButGrabar;
    private javax.swing.JButton jButMayMen;
    private javax.swing.JToggleButton jButMostrarOcultar;
    private javax.swing.JCheckBox jCheckBoxIncrementar;
    private javax.swing.JLabel jLabMayor;
    private javax.swing.JLabel jLabMenor;
    private javax.swing.JLabel jLabPromedioR;
    private javax.swing.JLabel jLabPromedioXc;
    private javax.swing.JLabel jLabTotalXl;
    private javax.swing.JLabel jLabTotalZ;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelprom;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinPosicion;
    private javax.swing.JTable jTableCircuitos;
    private javax.swing.JTextField jTextEstablecer;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextReactanciaCapacitiva;
    private javax.swing.JTextField jTextReactanciaInductiva;
    private javax.swing.JTextField jTextResistencia;
    // End of variables declaration//GEN-END:variables

    }


